artifacts_roots: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Abdoul1996/End-to-End-ML-Project/raw/main/research/WineQT.csv.zip
  local_data_file: artifacts/data_ingestion/WineQT.zip
  unzip_dir: artifacts/data_ingestion
